Jake Ardoin
4/30/2020

In [1]:
import numpy as np
import pandas as pd
import timeit
import time

In [2]:
time.time()

1588472283.5661833

In [3]:
#Problem 1.1
np.random.seed(int(time.time()))
dataa = np.random.randint(1,10000000,1000000)
datab = np.random.randint(1,10000000,1000000)
my_data = np.array([dataa,datab])
print(my_data)

[[5388324 4133096 8255716 ... 6622029 7132385 9883739]
 [4447912 6428829 4554372 ... 8700519 7890885 6125881]]


In [4]:
#Problem 1.2
np.savetxt('generated.csv', my_data ,fmt='%d', delimiter=',')

In [5]:
#Problem 1.3-1.5


class MyClass:

    #stores the results
    r = None
    a = None
    b = None

    def __init__(self):
        ar = np.loadtxt('generated.csv', dtype = np.int, delimiter=',')
        self.a = ar[0]
        self.b = ar[1]

    #merges any two columns, a, b, or r
    #param x: 'a', 'b' or 'r'
    #param y: 'a', 'b' or 'r'
    def merge(self, x, y):
        if x == y:
            return print("The x and y parameters cannot be the same")

        if x == 'a':
            x = self.a
        elif x == 'b':
            x = self.b
        elif x == 'r':
            x = self.r
        else:
            return print("The x parameter must be either \'a\', \'b\', or \'r\'")

        if y == 'a':
            y=self.a
        elif y=='b':
            y=self.b
        elif y == 'r':
            y = self.r
        else:
            return print("The y parameter must be either \'a\', \'b\', or \'r\'")

        d = np.concatenate((x,y), axis=None)
        self.r = np.array(d)

    #sorts either a, b, or r in place.
    #param x == 'a', 'b' or 'r'
    def sortInPlace(self, x):
        if x == 'a':
            self.a = np.sort(self.a)
        elif x == 'b':
            self.b = np.sort(self.b)
        elif x== 'r':
            self.r = np.sort(self.b)
        else:
            return print("The x parameter must be either \'a\', \'b\', or \'r\'")

    #find the unique values in a, b, or r and store in r
    #param x == 'a', 'b' or 'r'
    def getUnique(self, x):
        if x == 'a':
            x = self.a
        elif x == 'b':
            x = self.b
        elif x == 'r':
            x = self.r
        else:
            return print("The x parameter must be either \'a\', \'b\', or \'r\'")
        self.r = np.unique(x)

    #find set intersection of a and b then save results in r
    def intersectAB(self):
        self.r = np.intersect1d(self.a,self.b)

    #find the set difference of a and b and save the results in r
    def differenceAB(self):
        self.r = np.setdiff1d(self.a,self.b)

    #write the data a, b, and r to a csv
    #param fileName: filename to save to
    def dataToCSV(self, fileName):
        data = np.array([self.a,self.b,self.r])
        frame = pd.DataFrame(data)
        frame.to_csv(fileName, index=False)

    #counts the number of elements in x and prints the number
    #param x == 'a', 'b', or 'r'
    def printCount(self,x):
        if x == 'a':
            x = self.a
        elif x == 'b':
            x = self.b
        elif x == 'r':
            x = self.r
        else:
            return print("The x parameter must be either \'a\', \'b\', or \'r\'")
        print(len(x))

In [6]:
#to show it works
c = MyClass()
c.merge('a','b')
print(f'after merge: {c.r} \n size ={len(c.r)} \n')
c.sortInPlace('a')
print(f'after ainplace: {c.a}\n size ={len(c.r)} \n')
c.getUnique('b')
print(f'after bunique: {c.r}\n size ={len(c.r)} \n')
c.intersectAB()
print(f'after intersectAB: {c.r}\n size ={len(c.r)} \n')
c.differenceAB()
print(f'after diffAB: {c.r}\n size ={len(c.r)} \n')
c.dataToCSV('coutput.csv')
with open('coutput.csv', 'r') as file:
    for x in file:
        print(x)
r = c.printCount('r')



after merge: [5388324 4133096 8255716 ... 8700519 7890885 6125881] 
 size =2000000 

after ainplace: [      8      21      26 ... 9999983 9999985 9999990]
 size =2000000 

after bunique: [     22      23      29 ... 9999954 9999955 9999959]
 size =951425 

after intersectAB: [     29      85     157 ... 9999418 9999726 9999819]
 size =90415 

after diffAB: [      8      21      26 ... 9999983 9999985 9999990]
 size =861076 

0

[      8      21      26 ... 9999983 9999985 9999990]

[4447912 6428829 4554372 ... 8700519 7890885 6125881]

[      8      21      26 ... 9999983 9999985 9999990]

861076


In [7]:
#Problem 1.6

def procedure():
    my_class = MyClass()
    my_class.merge('a','b')
    my_class.getUnique('r')
    print(f'The unique values in the merged data are: {my_class.r}\n')
    print(f'The number of unique values: {len(my_class.r)}\n')
    my_class.differenceAB()
    print(f'The set difference is: {my_class.r}\n')
    print(f'The number of items in the set difference is: {len(my_class.r)}\n')
    my_class.intersectAB()
    print(f'The intersection of A and B is: {my_class.r}\n')
    print(f'The number of values in the intersection is: {len(my_class.r)}\n')

In [8]:
procedure()

The unique values in the merged data are: [      8      21      22 ... 9999983 9999985 9999990]

The number of unique values: 1812501

The set difference is: [      8      21      26 ... 9999983 9999985 9999990]

The number of items in the set difference is: 861076

The intersection of A and B is: [     29      85     157 ... 9999418 9999726 9999819]

The number of values in the intersection is: 90415



In [9]:
#Problem 1.7
def wrapper(func, *args, **kwargs):
    def wrapped():
        return func(*args, **kwargs)
    return wrapped

my_class = MyClass()
wrapped = wrapper(my_class.merge, 'a','b')
print(f'Merge function takes {timeit.timeit(wrapped, number=10)}s \n')
wrapped = wrapper(my_class.sortInPlace, 'r')
print(f'Sort function takes {timeit.timeit(wrapped, number=10)}s \n')
wrapped = wrapper(my_class.getUnique, 'r')
print(f'Unique function takes {timeit.timeit(wrapped, number=10)}s \n')
wrapped = wrapper(my_class.intersectAB)
print(f'Intersect functions takes {timeit.timeit(wrapped, number=10)}s \n')
wrapped = wrapper(my_class.differenceAB)
print(f'Difference functions takes {timeit.timeit(wrapped, number=10)}s \n')
wrapped = wrapper(my_class.dataToCSV, 'outputfile.csv')
print(f'DatatoCSV functions takes {timeit.timeit(wrapped, number=10)}s \n')
wrapped = wrapper(my_class.printCount, 'r')
print(f'PrintCount functions takes {timeit.timeit(wrapped, number=10)}s \n')

Merge function takes 0.027238022001256468s 

Sort function takes 0.8353879149981367s 

Unique function takes 0.10923791999812238s 

Intersect functions takes 3.1620034070001566s 

Difference functions takes 1.9960583780011802s 

DatatoCSV functions takes 0.008423343999311328s 

861076
861076
861076
861076
861076
861076
861076
861076
861076
861076
PrintCount functions takes 0.00020091799888177775s 



In [10]:
#Problem 1.8
print(f'*******The procedue time is {timeit.timeit(procedure, number=3)}s**********\n')

The unique values in the merged data are: [      8      21      22 ... 9999983 9999985 9999990]

The number of unique values: 1812501

The set difference is: [      8      21      26 ... 9999983 9999985 9999990]

The number of items in the set difference is: 861076

The intersection of A and B is: [     29      85     157 ... 9999418 9999726 9999819]

The number of values in the intersection is: 90415

The unique values in the merged data are: [      8      21      22 ... 9999983 9999985 9999990]

The number of unique values: 1812501

The set difference is: [      8      21      26 ... 9999983 9999985 9999990]

The number of items in the set difference is: 861076

The intersection of A and B is: [     29      85     157 ... 9999418 9999726 9999819]

The number of values in the intersection is: 90415

The unique values in the merged data are: [      8      21      22 ... 9999983 9999985 9999990]

The number of unique values: 1812501

The set difference is: [      8      21      26 ... 9